# Generated by Django 5.1 on 2024-08-09 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_topic_room_host_alter_room_name_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
